// Vocabulary Data
const vocabularyData = {
    chapter1: [
        { term: "Economics", definition: "The study of how a society uses scarce resources to produce and distribute goods and services." },
        { term: "Economic system", definition: "The way a government decides what gets produced and how it's distributed." },
        { term: "Capitalism", definition: "An economic system based on private ownership and competition." },
        { term: "Communism", definition: "An economic system where the government owns and controls almost everything." },
        { term: "Socialism", definition: "An economic system where major industries are owned or heavily controlled by the government." },
        { term: "Mixed economies", definition: "Economies that combine private ownership with government involvement." },
        { term: "Business", definition: "An organization that seeks profit by providing goods or services." },
        { term: "Not-for-profit organization", definition: "An organization focused on goals other than profit." },
        { term: "Entrepreneurs", definition: "People who combine resources to create goods or services for profit." },
        { term: "Strategic alliance", definition: "A cooperative agreement between businesses." },
        { term: "Relationship management", definition: "Building long-term relationships with customers and partners." },
        { term: "Factors of production", definition: "Resources used to make goods and services." },
        { term: "Capital", definition: "Tools, machinery, and buildings used in production." },
        { term: "Knowledge", definition: "The skills and talents of the workforce." },
        { term: "Knowledge workers", definition: "Workers who create and apply knowledge." },
        { term: "Productivity", definition: "How much output one worker can produce." },
        { term: "Market structure", definition: "The number of suppliers in a market." },
        { term: "Perfect competition", definition: "Many small firms, easy entry, similar products." },
        { term: "Monopolistic competition", definition: "Many firms selling similar but slightly different products." },
        { term: "Oligopoly", definition: "A few firms dominate the market." },
        { term: "Pure monopoly", definition: "One firm controls the entire market." },
        { term: "Barriers to entry", definition: "Factors that prevent new firms from entering a market." },
        { term: "Demand", definition: "How much people are willing to buy at different prices." },
        { term: "Demand curve", definition: "A graph showing quantity demanded at various prices." },
        { term: "Equilibrium", definition: "Where quantity supplied equals quantity demanded." },
        { term: "Costs", definition: "Expenses from producing goods or services." },
        { term: "Revenue", definition: "Money earned from sales." },
        { term: "Profit", definition: "Money left after all costs are paid." },
        { term: "Gross domestic product (GDP)", definition: "Total value of goods and services produced in a country yearly." },
        { term: "Economic growth", definition: "An increase in a nation's output." },
        { term: "Business cycles", definition: "Up-and-down changes in economic activity." },
        { term: "Recession", definition: "A decline in GDP for at least two quarters." },
        { term: "Full employment", definition: "Everyone who wants to work has a job." },
        { term: "Inflation", definition: "A rise in overall price levels." },
        { term: "Consumer Price Index (CPI)", definition: "Measures prices paid by consumers." },
        { term: "Producer Price Index (PPI)", definition: "Measures prices paid by producers." },
        { term: "Cost-push inflation", definition: "Inflation caused by rising production costs." },
        { term: "Demand-pull inflation", definition: "Inflation caused by high demand." },
        { term: "Purchasing power", definition: "What money can actually buy." },
        { term: "Fiscal policy", definition: "Government taxing and spending decisions." },
        { term: "Monetary policy", definition: "Government control of money supply and interest rates." },
        { term: "Expansionary policy", definition: "Policy that increases the money supply." },
        { term: "Contractionary policy", definition: "Policy that tightens the money supply." },
        { term: "Federal Reserve System (the Fed)", definition: "The U.S. central banking system." },
        { term: "Federal budget deficit", definition: "When government spends more than it collects." },
        { term: "National debt", definition: "Total of all past federal deficits." },
        { term: "Crowding out", definition: "Government spending replacing private spending." },
        { term: "Savings bonds", definition: "Small-denomination government bonds." },
        { term: "Frictional unemployment", definition: "Short-term unemployment between jobs." },
        { term: "Cyclical unemployment", definition: "Unemployment caused by economic downturns." },
        { term: "Seasonal unemployment", definition: "Unemployment tied to certain seasons." },
        { term: "Goods", definition: "Tangible products you can touch." },
        { term: "Services", definition: "Intangible products you can't touch or store." },
        { term: "Standard of living", definition: "What people can buy with their income." },
        { term: "Quality of life", definition: "Overall well-being and happiness." },
        { term: "Macroeconomics", definition: "The study of the economy as a whole." },
        { term: "Microeconomics", definition: "The study of individual households and firms." },
        { term: "Circular flow", definition: "Movement of money and resources between households, businesses, and government." },
        { term: "Demography", definition: "The study of population statistics." },
        { term: "Risk", definition: "The chance of losing time or money." }
    ]
};

// Chapters Data
const chapters = [
    { id: 'ch1', number: 1, title: 'Understanding Economic Systems and Business' },
    { id: 'ch2', number: 2, title: 'Making Ethical Decisions and Managing a Socially Responsible Business' },
    { id: 'ch3', number: 3, title: 'Competing in the Global Marketplace' },
    { id: 'ch4', number: 4, title: 'Forms of Business Ownership' },
    { id: 'ch5', number: 5, title: 'Entrepreneurship: Starting and Managing Your Own Business' },
    { id: 'ch6', number: 6, title: 'Management and Leadership in Today\'s Organizations' },
    { id: 'ch7', number: 7, title: 'Designing Organizational Structures' },
    { id: 'ch8', number: 8, title: 'Managing Human Resources and Labor Relations' },
    { id: 'ch9', number: 9, title: 'Motivating Employees' },
    { id: 'ch10', number: 10, title: 'Achieving World-Class Operations Management' },
    { id: 'ch11', number: 11, title: 'Creating Products and Pricing Strategies to Meet Customers\' Needs' },
    { id: 'ch12', number: 12, title: 'Distributing and Promoting Products and Services' },
    { id: 'ch13', number: 13, title: 'Using Technology to Manage Information' },
    { id: 'ch14', number: 14, title: 'Using Financial Information and Accounting' },
    { id: 'ch15', number: 15, title: 'Understanding Money and Financial Institutions' },
    { id: 'ch16', number: 16, title: 'Understanding Financial Management and Securities Markets' },
    { id: 'ch17', number: 17, title: 'Your Career in Business' }
];

// Sections Data
const sections = [
    { id: 'textbook', icon: 'fa-book-open', label: 'Textbook', class: 'textbook' },
    { id: 'study-guide', icon: 'fa-file-lines', label: 'Study Guide', class: 'study-guide' },
    { id: 'study-games', icon: 'fa-gamepad', label: 'Study Games', class: 'study-games' },
    { id: 'vocabulary', icon: 'fa-spell-check', label: 'Vocabulary', class: 'vocabulary' }
];
